src/main/java/br/edmtool/model/AccuracyByClass.java
package br.edmtool.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Version;

public class AccuracyByClass implements Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;
	@Version
	@Column(name = "version")
	private int version;
	
	@Column
    private double tpRate;
	@Column
    private double fpRate;
	@Column
    private double precision;
	@Column
    private double recall;
	@Column
    private double fMeasure;
	@Column
    private double mcc;
	@Column
    private double rocArea;
	@Column
    private double prcArea;
	@Column
	private String predicationClass;
	
	@ManyToOne
	private ClassificationModel modeloAccuracy;
	

	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(final int version) {
		this.version = version;
	}

	@Override
	public String toString() {
		String result = getClass().getSimpleName() + " ";
		if (id != null)
			result += "id: " + id;
		return result;
	}

	public double getTpRate() {
		return tpRate;
	}

	public void setTpRate(double tpRate) {
		this.tpRate = tpRate;
	}

	public double getFpRate() {
		return fpRate;
	}

	public void setFpRate(double fpRate) {
		this.fpRate = fpRate;
	}

	public double getPrecision() {
		return precision;
	}

	public void setPrecision(double precision) {
		this.precision = precision;
	}

	public double getRecall() {
		return recall;
	}

	public void setRecall(double recall) {
		this.recall = recall;
	}

	public double getfMeasure() {
		return fMeasure;
	}

	public void setfMeasure(double fMeasure) {
		this.fMeasure = fMeasure;
	}

	public double getMcc() {
		return mcc;
	}

	public void setMcc(double mcc) {
		this.mcc = mcc;
	}

	public double getRocArea() {
		return rocArea;
	}

	public void setRocArea(double rocArea) {
		this.rocArea = rocArea;
	}

	public double getPrcArea() {
		return prcArea;
	}

	public void setPrcArea(double prcArea) {
		this.prcArea = prcArea;
	}

	public String getPredicationClass() {
		return predicationClass;
	}

	public void setPredicationClass(String predicationClass) {
		this.predicationClass = predicationClass;
	}

	public ClassificationModel getModeloAccuracy() {
		return modeloAccuracy;
	}

	public void setModeloAccuracy(ClassificationModel modelo) {
		this.modeloAccuracy = modelo;
	}
}

src/main/java/br/edmtool/model/KnowledgeDiagnostic.java
package br.edmtool.model;

public enum KnowledgeDiagnostic {
	BAIXO_APROVEITAMENTO_GUESS, BAIXO_APROVEITAMENTO_SLIP, BAIXO_APROVEITAMENTO_UNKONW, 
    ALTO_APROVEITAMENTO_GUESS, ALTO_APROVEITAMENTO_SLIP, ALTO_APROVEITAMENTO_UNKONW, 
    PERDA_APROVEITAMENTO_GUESS, PERDA_APROVEITAMENTO_SLIP, PERDA_APROVEITAMENTO_UNKONW
}

src/main/java/br/edmtool/model/PredictionClass.java
package br.edmtool.model;

public interface PredictionClass {
	public static final String NAO = "NAO";
	public static final String SIM = "SIM";
}

src/main/java/br/edmtool/controller/ClassificationController.java
package br.edmtool.controller;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import br.edmtool.classification.NaiveBayesClassifier;
import br.edmtool.model.Classification;
import br.edmtool.model.ClassificationInstance;
import br.edmtool.service.ClassificationRegistration;
import br.edmtool.utils.Configuration;
import br.edmtool.utils.CrossValidationMethod;
import br.edmtool.utils.OsCheck;
import br.edmtool.utils.OsCheck.OSType;
import br.edmtool.utils.YamlConfigRunner;

// The @Model stereotype is a convenience mechanism to make this a request-scoped bean that has an
// EL name
// Read more about the @Model stereotype in this FAQ:
// http://www.cdi-spec.org/faq/#accordion6
@Model
@ViewScoped
@Named
public class ClassificationController {

	private Logger logger = LogManager.getRootLogger();

	@Inject
	private FacesContext facesContext;

	@Inject
	private ClassificationRegistration classificacaoRegistration;

	@Produces
	@Named
	private Classification newClassificacao;

	private CrossValidationMethod metodoSelecionado;

	private String valorSelecionado;

	public List<String> getValues() {
		return Arrays.asList("Year 2000", "Year 2010", "Year 2020");
	}

	public List<CrossValidationMethod> getMetodosValidacaoDesempenho() {
		List<CrossValidationMethod> listCrossValidMethod = new ArrayList<CrossValidationMethod>(2);
		listCrossValidMethod.add(new CrossValidationMethod("1", NaiveBayesClassifier.TEN_FOLD_CROSS_VALIDATION_DESC));
		listCrossValidMethod
				.add(new CrossValidationMethod("2", NaiveBayesClassifier.LEAVE_ONE_OUT_CROSS_VALIDATION_DESC));
		return listCrossValidMethod;
	}

	@PostConstruct
	public void initClassificacao() {
		newClassificacao = new Classification();
	}

	public void classifyStudents() {
		try {
			ExternalContext ec = FacesContext.getCurrentInstance().getExternalContext();
			String crossValidSelected = ec.getRequestParameterMap().get("crossValidSelected");

			if (crossValidSelected == null || crossValidSelected.isEmpty()) {
				FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR,
						"Antes de prosseguir, selecione o método de validação cruzada desejado.", null);
				facesContext.addMessage(null, m);

				return;
			}

			OSType operationalSystem = OsCheck.getOperatingSystemType();

			String dataDir = "";
			String configDir = "";

			logger.trace("Operational System Type :: " + OsCheck.getOperatingSystemType());

			switch (operationalSystem) {
			case Linux:
				dataDir = YamlConfigRunner.ROOT_DIR_LINUX;
				configDir = YamlConfigRunner.ROOT_DIR_LINUX + YamlConfigRunner.YAML_CONFIG_FILE;
				break;

			case Windows:
				dataDir = YamlConfigRunner.ROOT_DIR_WIN;
				configDir = YamlConfigRunner.ROOT_DIR_WIN + YamlConfigRunner.YAML_CONFIG_FILE;
				break;

			case MacOS:
				throw new Exception("MacOS distribution is not implemented yet");

			case Other:
				throw new Exception("Other's OS distribution is not implemented yet");

			default:
				throw new Exception("Operational system not detected");
			}

			Configuration config = new YamlConfigRunner().getSingletonInstance(configDir).getConfig();

			StudentMiner miner = new StudentMiner(
					dataDir.concat(config.getClassificationDataDir().concat(config.getTrainningDataFile())));

			Classification studentsClassification = miner.predictStudentsDropout(
					dataDir.concat(config.getClassificationDataDir()).concat(config.getTestDataFile()),
					Integer.valueOf(crossValidSelected));

			for (ClassificationInstance studentClassification : studentsClassification.getModelo().getInstanciaList()) {
				logger.trace("Estudante classificado no modelo:: " + studentClassification.getUserId());
			}

			classificacaoRegistration.registerAll(studentsClassification);

			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO,
					"Processo de classificação de alunos concluído com sucesso!", "Classificação realizada!");
			facesContext.addMessage(null, m);
		} catch (Exception e) {
			logger.error(e);
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR,
					"Ocorreu um erro no processo de classificação dos alunos. Verifique o log do sistema.",
					errorMessage);
			facesContext.addMessage(null, m);
		}

	}

	private String getRootErrorMessage(Exception e) {
		// Default to general error message that registration failed.
		String errorMessage = "Registration failed. See server log for more information";
		if (e.getMessage() == null) {
			// This shouldn't happen, but return the default messages
			return errorMessage;
		}

		// Start with the exception and recurse to find the root cause
		Throwable t = e;
		while (t != null) {
			// Get the message from the Throwable class instance
			errorMessage = t.getLocalizedMessage();
			t = t.getCause();
		}
		// This is the root cause message
		return errorMessage;
	}

	public CrossValidationMethod getMetodoSelecionado() {
		return metodoSelecionado;
	}

	public void setMetodoSelecionado(CrossValidationMethod metodoSelecionado) {
		this.metodoSelecionado = metodoSelecionado;
	}

	public String getValorSelecionado() {
		return valorSelecionado;
	}

	public void setValorSelecionado(String valorSelecionado) {
		this.valorSelecionado = valorSelecionado;
	}

}

src/main/java/br/edmtool/controller/StudentKnowledgeController.java
package br.edmtool.controller;

import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.enterprise.inject.Model;
import javax.enterprise.inject.Produces;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import br.edmtool.bkt.BKTBruteForceWrapper;
import br.edmtool.model.KnowledgeAnalysis;
import br.edmtool.model.StudentPerformance;
import br.edmtool.service.KnowledgeAnalysisRegistration;
import br.edmtool.utils.Configuration;
import br.edmtool.utils.OsCheck;
import br.edmtool.utils.OsCheck.OSType;
import br.edmtool.utils.YamlConfigRunner;

@Model
@ViewScoped
@Named
public class StudentKnowledgeController {
	
	private Logger logger = LogManager.getRootLogger();
	
	@Inject
	private FacesContext facesContext;

	@Inject
	private KnowledgeAnalysisRegistration analiseDesempenhoRegistration;

	@Produces
	@Named
	private KnowledgeAnalysis analiseDesempenho;

	@PostConstruct
	public void initAnaliseDesempenho() {
		analiseDesempenho = new KnowledgeAnalysis();
	}


	public void evaluateStudentPerformance() {
		try {
			OSType operationalSystem = OsCheck.getOperatingSystemType();
			
			String dataDir = "";
			String configDir = "";
			
			System.out.println(OsCheck.getOperatingSystemType());
			
			switch (operationalSystem) {
			case Linux:
				dataDir = YamlConfigRunner.ROOT_DIR_LINUX;
				configDir = YamlConfigRunner.ROOT_DIR_LINUX + YamlConfigRunner.YAML_CONFIG_FILE;
				break;

			case Windows:
				dataDir = YamlConfigRunner.ROOT_DIR_WIN;
				configDir = YamlConfigRunner.ROOT_DIR_WIN + YamlConfigRunner.YAML_CONFIG_FILE;
				break;
				
			case MacOS:
				throw new Exception("MacOS distribution is not implemented yet");
				
			case Other:
				throw new Exception("Other's OS distribution is not implemented yet");

			default:
				throw new Exception("Operational system not detected");
			}
			
			Configuration config = new YamlConfigRunner().getSingletonInstance(configDir).getConfig();
			
			BKTBruteForceWrapper bktWrapper = new BKTBruteForceWrapper();

			List<StudentPerformance> studentBKTList = bktWrapper.evaluateStudentPerformance(dataDir.concat(config.getBktDataDir()).concat(config.getBktDataFile()));
			
			Date dataAnalise = new Date();
			
			analiseDesempenho.setAlgorithm(bktWrapper.getAlgorithmName());
			analiseDesempenho.setDataset(config.getBktDataFile());
			analiseDesempenho.setInstancesTotal(studentBKTList.size());
			analiseDesempenho.setDate(dataAnalise);
			
			for (StudentPerformance studentBKT : studentBKTList) {
				logger.debug("Student data "+ studentBKT);
				studentBKT.setAnaliseDesempenho(analiseDesempenho);
				studentBKT.setDate(dataAnalise);
			}

			analiseDesempenho.setStudentPerformanceList(studentBKTList);

			analiseDesempenhoRegistration.registerAll(analiseDesempenho);

			logger.trace(studentBKTList.size() + " BKT students saved");

			List<KnowledgeAnalysis> studentsList = analiseDesempenhoRegistration.listStudentPerformance();

			logger.trace(studentsList.size() + " students saved");

			for (KnowledgeAnalysis studentBKT : studentsList) {
				logger.trace("BKT Student data "+ studentBKT);
			}

			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_INFO, "Processo de análise de desempenho de alunos concluído com sucesso!", "Análise de desempenho realizada.");
			logger.info("Processo de análise de desempenho de alunos concluído com sucesso! Análise de desempenho realizada.");
			
			facesContext.addMessage(null, m);
			analiseDesempenho = null;
		} catch (Exception e) {
			String errorMessage = getRootErrorMessage(e);
			FacesMessage m = new FacesMessage(FacesMessage.SEVERITY_ERROR, errorMessage,
					"Falha no processo de análise de desempenho de alunos");
			facesContext.addMessage(null, m);
			logger.error(e);
		}
	}

	private String getRootErrorMessage(Exception e) {
		// Default to general error message that registration failed.
		String errorMessage = "Registration failed. See server log for more information";
		if (e == null) {
			// This shouldn't happen, but return the default messages
			return errorMessage;
		}

		// Start with the exception and recurse to find the root cause
		Throwable t = e;
		while (t != null) {
			// Get the message from the Throwable class instance
			errorMessage = t.getLocalizedMessage();
			t = t.getCause();
		}
		// This is the root cause message
		return errorMessage;
	}

}

src/main/java/br/edmtool/data/ModeloBean.java
package br.edmtool.data;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

@ManagedBean
@RequestScoped
public class ModeloBean {
	private Logger logger = LogManager.getRootLogger();
	
    private int id;
    /**
    * Creates a new instance of ModeloBean
    */
    public ModeloBean() {
        try {
            this.id = Integer.parseInt((String)FacesContext
               .getCurrentInstance().getExternalContext()
               .getRequestParameterMap().get("id"));
            //by getting the id you can get more data
            
            logger.trace("Id Modelo " + this.id);
        }
        catch (Exception e) {
            this.id = 0;
            logger.error(e);
        }
    }
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
    
}

src/main/webapp/analisedesempenho.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://butterfaces.org/components"
	template="/WEB-INF/templates/default.xhtml"
	xmlns:rich="http://richfaces.org/rich">
	<ui:define name="content">
	<h:head>
		<link
			href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
			rel="stylesheet" />
			
			<link
				href="resources/css/edmtool.css"
				rel="stylesheet" />	
	</h:head>
	

<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
  <div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="#"></a>
  </div>
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="index.jsf">Início</a></li>
      <li><a href="classificacao.jsf">Classificação</a></li>
      <li><a href="analisedesempenho.jsf">Avaliação de Conhecimento</a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
  </div>
</nav>
<div class="container">
				<br/>
						<div class="page-header">
  <h1><small>Identificação de Necessidade de Reforço na Aprendizagem</small></h1>
</div>
					<div class="panel panel-primary">
					<div class="panel-heading">Processo de Avaliação de Conhecimento de Alunos</div>
					<div class="panel-body">
					
					
					<div align="left">
									<h:form id="reg">
					<br/>
						<b:commandLink id="btnAnaliseDesempenho"
							value="Avaliar conhecimento"
							glyphicon="glyphicon glyphicon-education"
							styleClass="btn btn-success" ajaxDisableLinkOnRequest="true"
							ajaxShowWaitingDotsOnRequest="true"
							ajaxHideGlyphiconOnRequest="false"
							ajaxDisableRenderRegionsOnRequest="true"
							ajaxProcessingGlyphicon="fa fa-refresh fa-spin"
							action="#{studentKnowledgeController.evaluateStudentPerformance()}"
							rendered="true">
						</b:commandLink>
						</h:form>
						</div>
			
			<br/>
			<b:messages globalOnly="false" showDetail="false" rendered="true" />
			<f:verbatim rendered="#{not empty listaAnaliseDesempenho}"><hr/></f:verbatim>
			<h:form id="details">
						<div class="#{listaAnaliseDesempenho.size() == 0 ? 'display: inline-block' : 'panel panel-default'}">
							<!-- Default panel contents -->
							<div class="#{listaAnaliseDesempenho.size() == 0 ? 'display: inline-block' : 'panel-heading'}"><h:outputLabel value="Avaliações realizadas" rendered="#{not empty listaAnaliseDesempenho}"/></div>
			
							<b:table id="tabelaAnaliseDesempenho" var="_analiseDesempenho"
								value="#{listaAnaliseDesempenho}" tableBordered="false"
								tableCondensed="false" tableStriped="true"
								ajaxDisableRenderRegionsOnRequest="false"
								rendered="#{not empty listaAnaliseDesempenho}">

								<b:column id="detailsColumn" label="">
									<b:commandLink id="comandLinkClassificacao" value=""
										glyphicon="glyphicon glyphicon-zoom-in"
										styleClass="btn btn-info btn-xs"
										ajaxDisableLinkOnRequest="true"
										ajaxShowWaitingDotsOnRequest="true"
										ajaxHideGlyphiconOnRequest="false"
										ajaxDisableRenderRegionsOnRequest="true"
										ajaxProcessingGlyphicon="fa fa-refresh fa-spin"
										action="detalhesanalisedesempenho.jsf" rendered="true">

										<f:param name="id" value="#{_analiseDesempenho.id}" />
									</b:commandLink>
								</b:column>
								<b:column id="idColumn" label="#">
            #{_analiseDesempenho.id}
                
            </b:column>

								<b:column id="dateColumn" label="Data">
								<h:outputText class="control-label"
									value="#{_analiseDesempenho.date}">
									<f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss"
										timeZone="America/Sao_Paulo" />
								</h:outputText>
                
            </b:column>

								<b:column id="algorithmColumn" label="Algoritmo">
                #{_analiseDesempenho.algorithm}
            </b:column>

								<b:column id="datasetColumn" label="Dados utilizados">
                #{_analiseDesempenho.dataset}
            </b:column>

								<b:column id="attributesColumn" label="Total de alunos">
                #{_analiseDesempenho.instancesTotal}
            </b:column>
							</b:table>
</div>

				</h:form>
				
			</div>

			</div>
			</div>
	</ui:define>
</ui:composition>

src/main/webapp/classificacao.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:b="http://butterfaces.org/components"
	template="/WEB-INF/templates/default.xhtml"
	xmlns:rich="http://richfaces.org/rich">
	<ui:define name="content">
		<h:head>
			<link
				href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
				rel="stylesheet" />

			<link href="resources/css/edmtool.css" rel="stylesheet" />
		</h:head>


		<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand" href="#"></a>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li class="active"><a href="index.jsf">Início</a></li>
						<li><a href="classificacao.jsf">Classificação</a></li>
						<li><a href="analisedesempenho.jsf">Avaliação de Conhecimento</a></li>
					</ul>
				</div>
				<!-- /.navbar-collapse -->
			</div>
		</nav>
		<div class="container">
			<br />
			<div class="page-header">
				<h1>
					<small>Classificação de Alunos em Risco de Evasão</small>
				</h1>
			</div>
			<div class="panel panel-primary">
				<div class="panel-heading">Processo de Classificação de Alunos</div>
				<div class="panel-body">
				<h:form id="reg">
					<div class="well" style="display: inline-block;">

						<div class="form-group row">
							<div>
								<label class="control-label col-form-label">Método de
									validação cruzada:</label>
							</div>

							<!-- radio button para seleção de método de validação de desempenho -->
							<div class="btn-group" data-toggle="buttons">
								<ui:repeat var="crossVal"
									value="#{classificationController.metodosValidacaoDesempenho}"
									varStatus="status">
									<label class="btn btn-primary"> <input type="radio"
										name="crossValidSelected"
										value="#{crossVal.idCrossValidationMethod}" />
										#{crossVal.crossValidationMethodDescription}
									</label>
								</ui:repeat>
							</div>
						</div>
					</div>

					<div align="left">
						
							<br />
							<b:commandLink id="btnClassificarAlunos"
								value="Classificar alunos"
								glyphicon="glyphicon glyphicon-education"
								styleClass="btn btn-success" ajaxDisableLinkOnRequest="true"
								ajaxShowWaitingDotsOnRequest="true"
								ajaxHideGlyphiconOnRequest="false"
								ajaxDisableRenderRegionsOnRequest="true"
								ajaxProcessingGlyphicon="fa fa-refresh fa-spin"
								action="#{classificationController.classifyStudents()}"
								rendered="true">
							</b:commandLink>
					</div>
</h:form>
					<br />
					<b:messages globalOnly="false" showDetail="false" rendered="true" />
					<f:verbatim rendered="#{not empty classificacoes}">
						<hr />
					</f:verbatim>
					<h:form id="details">
					<!-- 							<div class="panel panel-default"> -->
					<div
						class="#{classificacoes.size() == 0 ? 'display: inline-block' : 'panel panel-default'}">
						<!-- Default panel contents -->
						<div
							class="#{classificacoes.size() == 0 ? 'display: inline-block' : 'panel-heading'}">
							<h:outputLabel value="Classificações realizadas"
								rendered="#{not empty classificacoes}" />
						</div>


						<b:table id="tableClassifications" var="_classificacao"
							value="#{classificacoes}" tableBordered="false"
							tableCondensed="false" tableStriped="true"
							ajaxDisableRenderRegionsOnRequest="false"
							rendered="#{not empty classificacoes}">

							<b:column id="detailsColumn" label="">
								<b:commandLink id="comandLinkClassificacao" value=""
									glyphicon="glyphicon glyphicon-zoom-in"
									styleClass="btn btn-info btn-xs"
									ajaxDisableLinkOnRequest="true"
									ajaxShowWaitingDotsOnRequest="true"
									ajaxHideGlyphiconOnRequest="false"
									ajaxDisableRenderRegionsOnRequest="true"
									ajaxProcessingGlyphicon="fa fa-refresh fa-spin"
									action="modelo.jsf" rendered="true">

									<f:param name="id" value="#{_classificacao.id}" />
								</b:commandLink>
							</b:column>
							<b:column id="idColumn" label="#">
            #{_classificacao.id}
                
            </b:column>
							<b:column id="dateColumn" label="Data">
								<h:outputText class="control-label"
									value="#{_classificacao.modelo.date}">
									<f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss"
										timeZone="America/Sao_Paulo" />
								</h:outputText>
							</b:column>

							<b:column id="algorithmColumn" label="Algoritmo">
                #{_classificacao.modelo.algorithm}
            </b:column>

							<b:column id="relationColumn" label="Dados utilizados">
                #{_classificacao.relation}
            </b:column>

							<b:column id="attributesColumn" label="Total de atributos">
                #{_classificacao.attributesTotal}
            </b:column>

							<b:column id="instancesColumn" label="Total de alunos">
                #{_classificacao.instancesTotal}
            </b:column>

							<b:column id="correctColumn" label="Classificações corretas">

								<h:outputText
									value="#{_classificacao.modelo.correctlyClassified}">
									<f:convertNumber type="number" maxFractionDigits="0" />
								</h:outputText>
							</b:column>
							<b:column id="incorrectColumn" label="Classificações incorretas"
								styleClass="col-md-1">
								<h:outputText
									value="#{_classificacao.modelo.incorrectlyClassified}">
									<f:convertNumber type="number" maxFractionDigits="0" />
								</h:outputText>
							</b:column>

							<b:column id="crossValidationColumn"
								label="Método de validação cruzada">
                #{_classificacao.testMode}
            </b:column>

							<b:column id="accuracyColumn" label="Precisão">
								<h:outputText value="#{_classificacao.accuracy}">
									<f:convertNumber type="number" maxFractionDigits="2" />
								</h:outputText>%
            </b:column>
						</b:table>
					</div>
				</h:form>

				</div>

			</div>
		</div>
	</ui:define>
</ui:composition>